# Generated by Django 3.2.12 on 2022-03-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
    ]
